---
- name: Change local adm password
  hosts: all

  tasks:
  - name: Change Local ADM password at Windows Servers
    win_user:
      name: "{{ username }}"
      password: "{{ password }}"
      update_password: always
      password_never_expires: yes
      state: present
